### ISSUE TITLE
W6 CH3 #28题 （3）

### ISSUE THREAD

**Issue by Gserts** [zhongyl0430/2021-Autumn_Linear_Algebra#2]
有点难以理解这题里面 两条线方向向量 外积和平面法向量的位置关系，答案不知道怎么出来，希望习题课或者答案里能够详细讲一下，谢谢友良大哥-v-

**Comment by zhongyl0430** [comment]
Hi, 抱歉现在才回复. 
我在参考答案中 (P. 12 of Ch3_Ex) 写了点简单的解释: 
三维空间中, "只有一个向量"会同时垂直于两个不共线的向量. 
这里说的"只有一个向量"是指: 如果有两个这样的向量, 它们必然共线. 

注意: 仅对三维有效 (因为 3-2 = 1), 对 n(>3) 维无效 (因为 n -2 > 1). 

你看看可以不? 有需要, 可以在习题课上讲一下. 
期待你的回复.

**Comment by Gserts** [comment]
> Hi, 抱歉现在才回复. 我在参考答案中 (P. 12 of Ch3_Ex) 写了点简单的解释: 三维空间中, "只有一个向量"会同时垂直于两个不共线的向量. 这里说的"只有一个向量"是指: 如果有两个这样的向量, 它们必然共线.
> 
> 注意: 仅对三维有效 (因为 3-2 = 1), 对 n(>3) 维无效 (因为 n -2 > 1).
> 
> 你看看可以不? 有需要, 可以在习题课上讲一下. 期待你的回复.

了解了！刚刚有时间看了参考答案，我清楚之间的关系了。谢谢老师~
